# Font
font_family Iosevka Term
font_size 12.0

foreground #FFFFFF
background #004E98
selection_foreground #FFFFFF
selection_background #565759

cursor #FFFFFF
cursor_text_color #004E98

active_border_color #0054E3
active_tab_background #0054E3

color0 #000000
color1 #FF6B6B
color2 #60FF60
color3 #FFFF60
color4 #7DCFFF
color5 #FF80FF
color6 #40FFFF
color7 #C0C0C0
color8 #003366
color9 #FFA0A0
color10 #80FF80
color11 #FFFF80
color12 #A0C4FF
color13 #FFAAFF
color14 #80FFFF
color15 #FFFFFF
