theme[main_bg]="#009800"
theme[main_fg]="#FFFFFF"
theme[title]="#7DFF7D"
theme[hi_fg]="#FFFFFF"
theme[selected_bg]="#3DFF3D"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#5A5A5A"

theme[proc_misc]="#7DFF7D"
theme[cpu_box]="#3DFF3D"
theme[mem_box]="#3DFF3D"
theme[net_box]="#3DFF3D"
theme[proc_box]="#3DFF3D"
theme[div_line]="#3DFF3D"

theme[temp_start]="#3DFF3D"
theme[temp_mid]="#7DFF7D"
theme[temp_end]="#009800"

theme[cpu_start]="#3DFF3D"
theme[cpu_mid]="#7DFF7D"
theme[cpu_end]="#009800"

theme[free_start]="#3C9B3C"
theme[free_mid]="#5CBF5C"
theme[free_end]="#FFFFFF"

theme[cached_start]="#3DFF3D"
theme[cached_mid]="#7DFF7D"
theme[cached_end]="#009800"

theme[available_start]="#5CBF5C"
theme[available_mid]="#3C9B3C"
theme[available_end]="#009800"

theme[used_start]="#E67E5C"
theme[used_mid]="#C24531"
theme[used_end]="#5A0000"

theme[download_start]="#3C9B3C"
theme[download_mid]="#5CBF5C"
theme[download_end]="#FFFFFF"

theme[upload_start]="#7DFF7D"
theme[upload_mid]="#3DFF3D"
theme[upload_end]="#FFFFFF"
