font-family = Iosevka Term
font-size = 12

background = #009800
foreground = #FFFFFF
cursor-color = #FFFFFF
cursor-text = #009800
selection-background = #565759
selection-foreground = #FFFFFF

palette = 0=#000000
palette = 1=#FF6B6B
palette = 2=#60B2FF
palette = 3=#FFFF60
palette = 4=#7DFF7D
palette = 5=#FF80FF
palette = 6=#40FF40
palette = 7=#C0C0C0
palette = 8=#006600
palette = 9=#FFA0A0
palette = 10=#80C2FF
palette = 11=#FFFF80
palette = 12=#A0FFA0
palette = 13=#FFAAFF
palette = 14=#80FF80
palette = 15=#FFFFFF
