[colors]
[colors.primary]
background = "#004E98"
foreground = "#FFFFFF"

[colors.cursor]
text = "#004E98"
cursor = "#FFFFFF"

[colors.vi_mode_cursor]
text = "#004E98"
cursor = "#FFFFFF"

[colors.selection]
text = "#FFFFFF"
background = "#565759"

[colors.normal]
black = "#000000"
red = "#FF6B6B"
green = "#60FF60"
yellow = "#FFFF60"
blue = "#7DCFFF"
magenta = "#FF80FF"
cyan = "#40FFFF"
white = "#C0C0C0"

[colors.bright]
black = "#003366"
red = "#FFA0A0"
green = "#80FF80"
yellow = "#FFFF80"
blue = "#A0C4FF"
magenta = "#FFAAFF"
cyan = "#80FFFF"
white = "#FFFFFF"
