theme[main_bg]="#004E98"
theme[main_fg]="#FFFFFF"
theme[title]="#7DCFFF"
theme[hi_fg]="#FFFFFF"
theme[selected_bg]="#3D95FF"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#5A5A5A"

theme[proc_misc]="#7DCFFF"
theme[cpu_box]="#3D95FF"
theme[mem_box]="#3D95FF"
theme[net_box]="#3D95FF"
theme[proc_box]="#3D95FF"
theme[div_line]="#3D95FF"

theme[temp_start]="#3D95FF"
theme[temp_mid]="#7DCFFF"
theme[temp_end]="#004E98"

theme[cpu_start]="#3D95FF"
theme[cpu_mid]="#7DCFFF"
theme[cpu_end]="#004E98"

theme[free_start]="#3C9B3C"
theme[free_mid]="#5CBF5C"
theme[free_end]="#FFFFFF"

theme[cached_start]="#3D95FF"
theme[cached_mid]="#7DCFFF"
theme[cached_end]="#004E98"

theme[available_start]="#5CBF5C"
theme[available_mid]="#3C9B3C"
theme[available_end]="#004E98"

theme[used_start]="#E67E5C"
theme[used_mid]="#C24531"
theme[used_end]="#5A0000"

theme[download_start]="#3C9B3C"
theme[download_mid]="#5CBF5C"
theme[download_end]="#FFFFFF"

theme[upload_start]="#7DCFFF"
theme[upload_mid]="#3D95FF"
theme[upload_end]="#FFFFFF"
