"ui.background" = { background = "#004E98" }
"ui.text" = { foreground = "#FFFFFF" }
"ui.text.focus" = { foreground = "#FFFFFF" }
"ui.cursor" = { foreground = "#FFFFFF" }
"ui.cursor.match" = { foreground = "#FFFFFF" }
"ui.selection" = { background = "#565759", foreground = "#FFFFFF" }
"ui.virtual.whitespace" = { foreground = "#003366" }
"ui.virtual.ruler" = { foreground = "#003366" }
"ui.virtual.inlay-hint" = { foreground = "#003366" }
"ui.menu" = { background = "#004E98", foreground = "#FFFFFF" }
"ui.menu.selected" = { background = "#565759", foreground = "#FFFFFF" }
"ui.linenr" = { foreground = "#C0B000" }
"ui.linenr.selected" = { foreground = "#FFD700", background = "#565759" }
"ui.statusline" = { background = "#004E98", foreground = "#FFFFFF" }
"ui.statusline.inactive" = { background = "#004E98", foreground = "#003366" }
"ui.statusline.normal" = { background = "#0054E3", foreground = "#FFFFFF" }
"ui.statusline.insert" = { background = "#60FF60", foreground = "#000000" }
"ui.statusline.select" = { background = "#FF6B6B", foreground = "#000000" }
"ui.popup" = { background = "#004E98", foreground = "#FFFFFF" }
"ui.window" = { background = "#004E98", foreground = "#FFFFFF" }
"ui.help" = { background = "#004E98", foreground = "#FFFFFF" }
"ui.highlight" = { background = "#565759", foreground = "#FFFFFF" }
"ui.highlight.fram" = { foreground = "#FFFFFF", modifiers = ["bold"] }
"info" = { foreground = "#7DCFFF" }
"warning" = { foreground = "#FFFF60" }
"error" = { foreground = "#FF6B6B" }
"diagnostic" = { foreground = "#FF80FF" }

"markup.heading.marker" = { foreground = "#FF6B6B" }
"markup.heading.1" = { foreground = "#FF6B6B" }
"markup.heading.2" = { foreground = "#60FF60" }
"markup.heading.3" = { foreground = "#FFFF60" }
"markup.heading.4" = { foreground = "#0054E3" }
"markup.heading.5" = { foreground = "#FF80FF" }
"markup.heading.6" = { foreground = "#40FFFF" }
"markup.link.url" = { foreground = "#7DCFFF" }
"markup.link.text" = { foreground = "#7DCFFF" }
"markup.list" = { foreground = "#FFFFFF" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"comment" = { foreground = "#7DCFFF", modifiers = ["italic"] }
"constant" = { foreground = "#FF80FF" }
"constant.numeric" = { foreground = "#FFFF60" }
"constant.character.escape" = { foreground = "#FFA0A0" }
"constant.builtin" = { foreground = "#7DCFFF" }

"string" = { foreground = "#FFA0A0" }
"string.special" = { foreground = "#FFFF80" }
"string.special.symbol" = { foreground = "#FFFFFF" }

"constructor" = { foreground = "#FF80FF" }
"function" = { foreground = "#FFFF60" }
"function.builtin" = { foreground = "#FFFF60" }
"function.macro" = { foreground = "#FFA0A0" }
"function.method" = { foreground = "#FFFF60" }
"function.special" = { foreground = "#FFFF60" }

"keyword" = { foreground = "#FF6B6B" }
"keyword.directive" = { foreground = "#FFA0A0" }
"keyword.control" = { foreground = "#FF6B6B" }
"keyword.control.conditional" = { foreground = "#FF6B6B" }
"keyword.control.repeat" = { foreground = "#FF6B6B" }
"keyword.control.import" = { foreground = "#FF6B6B" }
"keyword.control.return" = { foreground = "#FF6B6B" }
"keyword.control.exception" = { foreground = "#FFA0A0" }
"keyword.function" = { foreground = "#FFA0A0" }
"keyword.operator" = { foreground = "#0054E3" }

"label" = { foreground = "#FFFF60" }
"namespace" = { foreground = "#FF80FF" }
"operator" = { foreground = "#FFFFFF" }
"property" = { foreground = "#7DCFFF" }
"punctuation" = { foreground = "#C0C0C0" }
"punctuation.special" = { foreground = "#FFFF60" }
"tag" = { foreground = "#FF6B6B" }
"type" = { foreground = "#60FF60" }
"type.builtin" = { foreground = "#60FF60" }
"type.enum" = { foreground = "#60FF60" }
"variable" = { foreground = "#FFFFFF" }
"variable.builtin" = { foreground = "#FFA0A0" }
"variable.parameter" = { foreground = "#FFFF60" }
"variable.other.member" = { foreground = "#FFFFFF" }
