general {
    border_size = 1
    col.active_border = rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(3D95FF) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) 35deg
    col.inactive_border = rgb(716F64)
}

group {
    col.border_active = rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(3D95FF) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) rgb(0054E3) 35deg
    col.border_inactive = rgb(716F64)
}

# Position Walker at bottom-left like XP Start menu
windowrule = move 0 570, match:title ^Walker$
windowrule = size 320 480, match:title ^Walker$

