# Font
font_family Lucida Console
font_size 12.0

foreground #FFFFFF
background #004E98
selection_foreground #FFFFFF
selection_background #3D95FF

cursor #FFFFFF
cursor_text_color #004E98

active_border_color #0054E3
active_tab_background #0054E3

color0 #000000
color1 #C24531
color2 #3C9B3C
color3 #E6C340
color4 #0054E3
color5 #8E3C9B
color6 #2B9B9B
color7 #C0C0C0
color8 #5A5A5A
color9 #E67E5C
color10 #5CBF5C
color11 #F0D060
color12 #3D95FF
color13 #B060C0
color14 #5CC0C0
color15 #FFFFFF
